name:                aoc19
version:             0.1.0.0
github:              "benjaminweb/aoc19"
license:             BSD3
author:              "Benjamin Weber"
maintainer:          "mail@bwe.im"
copyright:           "2019 Benjamin Weber"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: "See README.md"

dependencies:
- base >= 4.7 && < 5
- bytestring
- split
- text
- optics
- optics-core
- containers

library:
  source-dirs: src
  exposed-modules:
    - Day1
    - Day2
    - Day3
    - Day4
    - Day5
    - IntCode

tests:
  doctest:
    main: doctest-driver.hs
    source-dirs:
      - test/doctest
    dependencies:
      - doctest
      - doctest-discover

  hspec:
    main:                Spec.hs
    source-dirs:         test/hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc19
      - hspec
